### ISSUE TITLE
树莓派3b+ ssh 一连就报错

### ISSUE THREAD

**Issue by keac** [ehang-io/nps-mux#1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x12464]

goroutine 34 [running]:
ehang.io/nps/lib/mux.(*ReceiveWindowQueue).Pop(0x21aa0d8, 0x513eb0, 0x216c2d0, 0xe716f753)
	/home/travis/gopath/src/github.com/ehang-io/nps/lib/mux/queue.go:254 +0x48
ehang.io/nps/lib/mux.(*ReceiveWindow).readFromQueue(0x21aa0c0, 0x21ca024, 0x4, 0x4, 0x1, 0x26214, 0xa48388, 0x0)
	/home/travis/gopath/src/github.com/ehang-io/nps/lib/mux/conn.go:346 +0x230
ehang.io/nps/lib/mux.(*ReceiveWindow).Read(0x21aa0c0, 0x21ca024, 0x4, 0x4, 0x1, 0xa48388, 0x1, 0x32)
	/home/travis/gopath/src/github.com/ehang-io/nps/lib/mux/conn.go:329 +0x58
ehang.io/nps/lib/mux.(*conn).Read(0x20fa060, 0x21ca024, 0x4, 0x4, 0x1b3d4, 0x0, 0x76f8cdf8)
	/home/travis/gopath/src/github.com/ehang-io/nps/lib/mux/conn.go:63 +0xb0
ehang.io/nps/lib/conn.(*Conn).Read(0x20d80a0, 0x21ca024, 0x4, 0x4, 0x3f888, 0x1309e4, 0x4)
	/home/travis/gopath/src/github.com/ehang-io/nps/lib/conn/conn.go:269 +0x128
io.ReadAtLeast(0x6a61a8, 0x20d80a0, 0x21ca024, 0x4, 0x4, 0x4, 0x0, 0x1b8a0, 0x19138)
	/home/travis/.gimme/versions/go1.13.linux.amd64/src/io/io.go:310 +0x6c
io.ReadFull(...)
	/home/travis/.gimme/versions/go1.13.linux.amd64/src/io/io.go:329
encoding/binary.Read(0x6a61a8, 0x20d80a0, 0x6ad940, 0xa51b50, 0x5167c8, 0x21ca020, 0x6, 0x14)
	/home/travis/.gimme/versions/go1.13.linux.amd64/src/encoding/binary/binary.go:165 +0x378
ehang.io/nps/lib/conn.(*Conn).GetLen(...)
	/home/travis/gopath/src/github.com/ehang-io/nps/lib/conn/conn.go:101
ehang.io/nps/lib/conn.(*Conn).getInfo(0x20d80a0, 0x50f978, 0x20dc008, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ehang-io/nps/lib/conn/conn.go:238 +0x100
ehang.io/nps/lib/conn.(*Conn).GetLinkInfo(...)
	/home/travis/gopath/src/github.com/ehang-io/nps/lib/conn/conn.go:148
ehang.io/nps/client.(*TRPClient).handleChan(0x20f6140, 0x6ae030, 0x20fa060)
	/home/travis/gopath/src/github.com/ehang-io/nps/client/client.go:169 +0x78
created by ehang.io/nps/client.(*TRPClient).newChan
	/home/travis/gopath/src/github.com/ehang-io/nps/client/client.go:164 +0xe8

**Expected behavior**

**Screenshots or logs**
Add screenshots or logs to help explain your problem.

**Server (please complete the following information):**
 - OS: [e.g. Centos, Windows]
 - ARCH: [e.g. Amd64, Arm]
 - Tunnel [e.g. TCP, HTTP]
 - Version [e.g. 0.24.0]

**Client (please complete the following information):**
 - OS: [e.g. Centos, Windows]
 - ARCH: [e.g. Amd64, Arm]
 - Tunnel [e.g. TCP, HTTP]
 - Version [e.g. 0.24.0]

**Additional context**

**Comment by ffdfgdfg** [comment]
你用的是arm而不是arm64？

**Comment by ffdfgdfg** [comment]
@keac 麻烦再试试，文件已更新，我这边测arm没问题，如果还有的话再详细的说下是armv6还是v7
以及详细的配置

**Comment by keac** [comment]
没有问题了，非常完美

**Comment by ffdfgdfg** [comment]
好的感谢反馈
